services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"   # REST API 접속용
      - "9600:9600"   # Performance Analyzer (선택)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"  # 웹 브라우저로 접속할 포트
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
  db:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eugenejang
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: mydb
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jiniixz@naver.com
      PGADMIN_DEFAULT_PASSWORD: 12341234
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
